apiVersion: v1
kind: Service
metadata:
  name: agent-win
  labels:
    app: agent-win
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: agent-win
spec:
  serviceName: agent-win
  replicas: 1
  selector:
    matchLabels:
      app: agent-win
  template:
    metadata:
      labels:
        app: agent-win
        version: "1.0"
    spec:
      containers:
      - name: agent-win
        image: georgd.azurecr.io/pipeline-agent:windows
        imagePullPolicy: IfNotPresent
        env:
          - name: VSTS_AGENT_INPUT_URL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: azp_url
          - name: VSTS_AGENT_INPUT_AUTH
            value: 'pat'
          - name: VSTS_AGENT_INPUT_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: azp_token
          - name: VSTS_AGENT_INPUT_POOL
            value: 'Container'
          - name: RUN_ONCE
            value: 'TRUE'
        # volumeMounts:
        # - mountPath: /var/run/docker.sock
        #   name: docker-volume
      imagePullSecrets:
        - name: azurecr
      tolerations:
        - key: kubernetes.io/os
          operator: Equal
          value: windows
          effect: NoSchedule
      nodeSelector:
        kubernetes.io/os: windows
      # volumes:
      # - name: docker-volume
      #   hostPath:
      #     path: /var/run/docker.sock