trigger: none

parameters:
- name: AgentPlatform
  displayName: Agent Platform
  type: string
  default: Windows
  values:
    - Windows
    - Linux
- name: PoolName
  displayName: Pool Name
  type: string

variables:
  poolId: 1

pool:
  vmImage: ubuntu-latest

steps:
- task: HelmInstaller@0
  inputs:
    helmVersion: '3.8.0'
    installKubectl: false
- pwsh: |
    $poolId = common/GetPoolId.ps1 -AzureDevOpsOrganization $(AzureDevOpsOrganization) -AzureDevOpsPersonalAccessToken $(AzureDevOpsToken) -PoolName ${{ parameters.PoolName }}
    Write-Host "##vso[task.setvariable variable=poolId]$poolId"
  displayName: Get PoolId from PoolName
- task: HelmDeploy@0
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'aks-mixed'
    command: 'install'
    chartType: 'FilePath'
    chartPath: 'helm'
    overrideValues: 'poolId='