parameters:
- name: DownloadAgent
  displayName: Download and Install Latest Pipeline Agent
  type: boolean
  default: False
 
jobs:
- job: 'BuildAgentImage'
  timeoutInMinutes: 90

  pool:
    vmImage: 'windows-latest'

  variables:
    baseImageName: 'mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019'
    imageName: 'containeragent.azurecr.io/pipeline-agent:windows'
    sourceDir : '$(build.SourcesDirectory)\\windows\\'

  steps:
  - powershell: |
     windows/DownloadAgent.ps1 -AzureDevOpsOrganization $(AzureDevOpsOrganization) -AzureDevOpsPersonalAccessToken $(AzureDevOpsToken) -DestinationDirectory $(Build.Artifact)
    condition: eq(parameters.DownloadAgent,true) 
  - task: Docker@2
    inputs:
      containerRegistry: 'containeragent'
      command: 'login'
  - powershell: |
      windows/BuildAgentImage.ps1 -WorkingDir $(build.ArtifactStagingDirectory) -SourceDir $(sourceDir) -BaseImage $(baseImageName) -AgentImage $(imageName) -PushImage
      