trigger: none

parameters:
- name: DownloadAgent
  displayName: Download and Install Latest Pipeline Agent
  type: boolean
  default: False

- name: AgentImage
  displayName: Pipeline Agent Image
  type: string
  default: windows-2019
  values:
    - windows-2019
    - windows-2022

variables:
  baseImageName: 'mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019'
  imageRepository: 'pipeline-agent'
  containerRegistry: 'containeragent'
  sourceDir : '$(build.SourcesDirectory)\\windows\\'
  workingDir : '$(build.ArtifactStagingDirectory)\\agent\\'
  dockerfilePath: '$(build.ArtifactStagingDirectory)\\agent\\Dockerfile'
  download: $[${{ parameters.DownloadAgent }}]
  agentPackage: 'none'
  tag: 'windows'
  # vmImageName: $[${{ parameters.AgentImage }}]
  vmImageName: 'windows-2022'

jobs:
- job: 'BuildAgentImage'
  timeoutInMinutes: 90

  pool:
    vmImage: $(vmImageName)

  steps:
  - powershell: |
     $package = windows/DownloadAgent.ps1 -AzureDevOpsOrganization $(AzureDevOpsOrganization) -AzureDevOpsPersonalAccessToken $(AzureDevOpsToken) -DestinationDirectory $(Build.ArtifactStagingDirectory)
     Write-Host "##vso[task.setvariable variable=agentPackage]$package"
    condition: eq(variables.download,true) 
    displayName: 'Download Agent Package'
  - powershell: |
     $psVersionTable
     $tag = windows/BuildAgentImage.ps1 -WorkingDir $(workingDir) -SourceDir $(sourceDir) -AgentPackage $(agentPackage)
     Write-Host "##vso[task.setvariable variable=tag]$tag"
  - task: Docker@2
    displayName: Build Windows Pipeline Agent Image
    inputs:
      containerRegistry: '$(containerRegistry)'
      repository: '$(imageRepository)'
      command: 'build'
      Dockerfile: $(dockerfilePath)
      tags: '$(tag)'
      arguments: '--build-arg BASE=$(baseImageName)'
  - task: Docker@2
    displayName: Push Windows Pipeline Agent Image
    inputs:
      containerRegistry: $(containerRegistry)
      repository: '$(imageRepository)'
      command: 'push'
      tags: '$(tag)'
      addPipelineData: true
      
      