# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

parameters:
- name: VSVersion
  displayName: Visual Studio Version
  type: string
  default: VS2019
  values:
  - VS2019
  - VS2017

- name: SKU
  displayName: Visual Studio SKU
  type: string
  default: Professional
  values: 
  - Professional
  - Enterprise

jobs:
- job: 'BuildVisualStudioImage'
  timeoutInMinutes: 90

  pool:
    name: default

  variables:
    imageName: $[lower('${{ parameters.VSVersion }}-${{ parameters.SKU }}')]
    imageNameBuild: '$(imageName):$(build.buildId)'
    imageNameLatest: '$(imageName):latest'
    dockerFile: 'windows/${{ parameters.VSVersion }}Container/Dockerfile.${{ parameters.SKU }}'
    buildArguments: '-m 2GB'

  steps:
  - powershell: |
      docker build -f $(dockerFile) -t $(dockerId).azurecr.io/$(imageNameBuild) -t $(dockerId).azurecr.io/$(imageNameLatest) $(buildArguments) windows
      docker login -u $(dockerId) -p $(password) $(dockerId).azurecr.io
      docker push $(dockerId).azurecr.io/$(imageNameBuild)
      docker push $(dockerId).azurecr.io/$(imageNamelatest)
