# Build Azure Pipeline Agent Container Image
# The pipeline get's two input parameters
# Parameter: VS Version (Which Version of Visual Studio should be used for the image)
#            Supported Version: 2017, 2019
# Parameter: SKU - Enterprise or Professional Version of Visual Studio
#

parameters:
- name: VSVersion
  displayName: Visual Studio Version
  type: string
  default: VS2019
  values:
  - VS2019
  - VS2017

- name: SKU
  displayName: Visual Studio SKU
  type: string
  default: Professional
  values: 
  - Professional
  - Enterprise

trigger: none

jobs:
- job: 'BuildVisualStudioImage'
  timeoutInMinutes: 90

  pool:
    name: default

  variables:
    imageName: $[lower('${{ parameters.VSVersion }}-${{ parameters.SKU }}')]
    imageNameBuild: '$(imageName):$(build.buildId)'
    imageNameLatest: '$(imageName):latest'
    dockerFile: 'windows/${{ parameters.VSVersion }}Container/Dockerfile.${{ parameters.SKU }}'
    buildArguments: '-m 2GB'

  steps:
  - powershell: |
      docker build -f $(dockerFile) -t $(dockerId).azurecr.io/$(imageNameBuild) -t $(dockerId).azurecr.io/$(imageNameLatest) $(buildArguments) windows
      docker login -u $(dockerId) -p $(password) $(dockerId).azurecr.io
      docker push $(dockerId).azurecr.io/$(imageNameBuild)
      docker push $(dockerId).azurecr.io/$(imageNamelatest)
