trigger: none

parameters:
- name: PoolName
  displayName: Pool Name
  type: string
  default: linux-container
  values:
    - linux-container
- name: AgentImage
  displayName: Agent Image
  type: string
  default: ubuntu-22.04
  values:
    - ubuntu-20.04
    - ubuntu-22.04
- name: CheckLatest
  displayName: Check for latest Image
  type: boolean
  default: true
- name: Repo
  displayName: Agent Repo
  type: string
  default: georgmcaps
  values:
    - containeragent
    - georgd
    - georgmcaps

variables:
- group: AzureDevOps
- name: poolId
  value: 0
- name: chartPath
  value: 'linux/helm'
- name: checkLatest
  value: $[${{ parameters.CheckLatest }}]

pool:
  vmImage: ubuntu-latest

steps:
- task: HelmInstaller@0
  inputs:
    helmVersion: '3.8.0'
    installKubectl: false
- pwsh: |
    $poolId = common/GetPoolId.ps1 -AzureDevOpsOrganization $(AzureDevOpsOrganization) -AzureDevOpsPersonalAccessToken $(AzureDevOpsToken) -PoolName ${{ parameters.PoolName }}
    Write-Host "##vso[task.setvariable variable=poolId]$poolId"
    [System.Uri] $uri = [System.Uri]::new("$(AzureDevOpsOrganization)")
    $namespace="{0}-pool-{1}" -f $uri.Segments[-1], $poolId
    Write-Host "Poolid:$poolId"
    Write-Host "##vso[task.setvariable variable=namespace]$namespace"
  displayName: Get PoolId from PoolName
- task: AzureCLI@2
  inputs:
    azureSubscription: 'MCAPS-CH-georgd(d0871d2e-75c2-4b10-bd2c-38f80979d9cb)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $tags = (az acr repository show-tags --name ${{parameters.repo}} --repository pipeline-agent --output tsv --orderby time_desc)
      $AgentImage = $tags | Where-Object { $_ -match "${{parameters.AgentImage}}-\d.\d+.\d" } | Select-Object -First 1
      Write-Host "##vso[task.setvariable variable=agentImage]$AgentImage"
  condition: eq(variables.checkLatest, true)
  displayName: Find last Image Tag
- pwsh: |
    $AgentImage = "${{parameters.AgentImage}}-latest"
    Write-Host "##vso[task.setvariable variable=agentImage]$AgentImage"
  displayName: Using the 'latest' Image Tag
  condition: eq(variables.checkLatest, false)
- pwsh: |
    Write-Host "Using Image:$(agentImage)"
- task: HelmDeploy@0
  enabled: true
  condition: ne(variables.poolId, 0)
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'aks-mixed'
    command: 'install'
    chartType: 'FilePath'
    chartPath: '$(chartPath)'
    releaseName: '$(namespace)'
    overrideValues: 'repo=${{parameters.repo}}.azurecr.io,poolId=$(poolId),poolName=${{parameters.PoolName}},tag=$(AgentImage),namespace=$(namespace),azpUrl=$(AzureDevOpsOrganization),azpToken=$(AzureDevOpsToken)'