trigger: none

parameters:
- name: PoolName
  displayName: Pool Name
  type: string
  default: windows-2022-container
  values:
    - windows-2019-container
    - windows-2022-container
- name: AgentImage
  displayName: Agent Image
  type: string
  default: windows-2022-2.217.2
- name: Repo
  displayName: Agent Repo
  type: string
  default: georgd
  values:
    - containeragent
    - georgd
    
variables:
- group: AzureDevOps
- name: poolId
  value: 0
- name: chartPath
  value: 'windows/helm'

pool:
  vmImage: ubuntu-latest

steps:
- task: HelmInstaller@0
  inputs:
    helmVersion: '3.8.0'
    installKubectl: false
- pwsh: |
    $poolId = common/GetPoolId.ps1 -AzureDevOpsOrganization $(AzureDevOpsOrganization) -AzureDevOpsPersonalAccessToken $(AzureDevOpsToken) -PoolName ${{ parameters.PoolName }}
    Write-Host "##vso[task.setvariable variable=poolId]$poolId"
    [System.Uri] $uri = [System.Uri]::new("$(AzureDevOpsOrganization)")
    $namespace="{0}-pool-{1}" -f $uri.Segments[-1], $poolId
    Write-Host "##vso[task.setvariable variable=namespace]$namespace"
  displayName: Get PoolId from PoolName
- task: HelmDeploy@0
  condition: ne(variables.poolId, 0)
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'aks-mixed'
    command: 'install'
    chartType: 'FilePath'
    chartPath: '$(chartPath)'
    releaseName: '$(namespace)'
    overrideValues: 'repo=${{parameters.repo}}.azurecr.io,poolId=$(poolId),poolName=${{parameters.PoolName}},tag=${{parameters.AgentImage}},namespace=$(namespace),azpUrl=$(AzureDevOpsOrganization),azpToken=$(AzureDevOpsToken)'