trigger: none

parameters:
- name: PoolName
  displayName: Pool Name
  type: string
  default: default
- name: AgentPlatform
  displayName: Agent Platform
  type: string
  default: Windows
  values:
    - Windows
    - Linux
- name: AgentImage
  displayName: Agent Image
  type: string
  default: windows-2022-latest
  values:
    - ubuntu-1804-latest
    - ubuntu-2004-latest
    - windows-2019-latest
    - windows-2022-latest

variables:
  poolId: 0
  chartPath: '$[${{ parameters.AgentPlatform}}]/helm'

pool:
  vmImage: ubuntu-latest

steps:
- task: HelmInstaller@0
  inputs:
    helmVersion: '3.8.0'
    installKubectl: false
- pwsh: |
    $poolId = common/GetPoolId.ps1 -AzureDevOpsOrganization $(AzureDevOpsOrganization) -AzureDevOpsPersonalAccessToken $(AzureDevOpsToken) -PoolName ${{ parameters.PoolName }}
    Write-Host "##vso[task.setvariable variable=poolId]$poolId"
    [System.Uri] $uri = [System.Uri]::new($(AzureDevOpsOrganization))
    $namespace="{0}-pool-{1}" -f $uri.Segments[-1], $poolId
    Write-Host "##vso[task.setvariable variable=namespace]$namespace"
  displayName: Get PoolId from PoolName
- task: HelmDeploy@0
  condition: ne($(poolId), 0)
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'aks-mixed'
    command: 'install'
    chartType: 'FilePath'
    chartPath: '$(chartPath)'
    overrideValues: 'poolId=$(poolId),poolName=${{parameters.PoolName}},tag=${{parameters.AgentImage}},namespace=$(namespace),azpUrl=$(AzureDevOpsOrganization),azpToken=$(AzureDevOpsToken)'