trigger: none

parameters:
- name: image
  displayName: Pool Image
  type: string
  default: windows-latest
  values:
  - windows-latest
  - windows-2019
  - windows-2022
  - ubuntu-latest
  - macOS-latest

variables:
  baseImageName: 'mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019'

jobs:
- job: build
  displayName: build
  pool: 
    vmImage: ${{ parameters.image }}
  steps:
  - pwsh: |
      Write-Host "BaseImage: $(baseImageName)"

