trigger: none

parameters:
- name: image
  displayName: Pool Image
  type: string
  default: windows-latest
  values:
  - windows-latest
  - windows-2019
  - windows-2022
  - ubuntu-latest
  - macOS-latest


jobs:
- job: build
  displayName: build
  pool: 
    vmImage: ${{ parameters.image }}
  steps:
  - pwsh: echo building $(Build.BuildNumber) with ${{ parameters.image }}

