trigger: none

parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-18.04
  values:
  - windows-18.04
  - windows-20.04

variables:
  dockerFile: 'none'
  tag: 'none'

jobs:
- job: build
  displayName: build
  pool: 
    vmImage: ${{ parameters.image }}
  steps:
  - pwsh: |
      switch ('${{ parameters.image }}') { `
        'ubuntu-18.04' { $dockerFile = 'ubuntu-1804'; break } `
        'windows-2022' { $dockerFile = 'ubuntu-2004'; break } `
      }
      Write-Host "$dockerFile"
      "##vso[task.setvariable variable=dockerFile]$dockerFile"
      $tag = '${{ parameters.image }}'
      "##vso[task.setvariable variable=tag]$tag"
    displayName: Selecting Agent Base Image
  - pwsh: |
      Write-Host "Dockerfile: $(dockerFile)"
      Write-Host "Tag: $(tag)"

