trigger: none

parameters:
- name: image
  displayName: Pool Image
  type: string
  default: windows-2019
  values:
  - windows-2019
  - windows-2022

variables:
  baseImageName: 'mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019'

jobs:
- job: build
  displayName: build
  pool: 
    vmImage: ${{ parameters.image }}
  steps:
  - pwsh: |
      switch ('${{ parameters.image }}') { `
        'windows-2019' { $baseImageName = 'mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019'; break } `
        'windows-2022' { $baseImageName = 'mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2022'; break } `
      }
      Write-Host "$baseImageName"
  - pwsh: |
      Write-Host "BaseImage: $(baseImageName)"

