trigger: none

parameters:
- name: ImageHash
  displayName: ImageHash of the image to sign
  type: string
- name: ContainerRegistry
  displayName: Container Registry Service Connection
  default: georgd
  values:
    - georgd
    - gdcontaineragent

variables:
- name: vmImage
  value: 'windows-latest'
- name: notationVersion
  value: '1.0.0-rc.7'
- name: notation_kv_version
  value: '1.0.0-rc.3'

jobs:
- job: 'SignAgentImage'
  displayName: Sign Agent Image
  pool:
      vmImage: $(vmImage)
    
  steps:
    - pwsh: |
        Invoke-WebRequest -Uri "https://github.com/notaryproject/notation/releases/download/v$(notationVersion)/notation_$(notationVersion)_windows_amd64.zip" -OutFile $(Build.ArtifactStagingDirectory)\notation.zip
        Unblock-File -Path $(Build.ArtifactStagingDirectory)\notation.zip
        Expand-Archive -Path $(Build.ArtifactStagingDirectory)\notation.zip -DestinationPath $(Build.ArtifactStagingDirectory)\notation\ -Force
        Get-ChildItem $(Build.ArtifactStagingDirectory)\notation\
      displayName: 'Download Notation $(notationVersion) Package'
    - pwsh: |
        $installPath = "${env:AppData}\notation\plugins\azure-kv"
        # download zip file and checksum
        $checksumFile = "notation-azure-kv_$(notation_kv_version)_checksum.txt"
        $zipFile = "notation-azure-kv_$(notation_kv_version)_windows_amd64.zip"
        Write-Host "https://github.com/Azure/notation-azure-kv/releases/download/v$(notation_kv_version)/${checksumFile}"
        Write-Host "https://github.com/Azure/notation-azure-kv/releases/download/v$(notation_kv_version)/${zipFile}"
        Invoke-WebRequest -Uri "https://github.com/Azure/notation-azure-kv/releases/download/v$(notation_kv_version)/${checksumFile}" -OutFile ${checksumFile}
        Invoke-WebRequest -Uri "https://github.com/Azure/notation-azure-kv/releases/download/v$(notation_kv_version)/${zipFile}" -OutFile ${zipFile}
        # validate checksum
        $checksum = (Get-Content ${checksumFile} | Select-String -List ${zipFile}).Line.Split() | Where-Object {$_}
        If ($checksum[0] -ne (Get-FileHash -Algorithm SHA256 $checksum[1]).Hash) {
          throw "$($checksum[1]): Failed"
        }
        # install the plugin
        mkdir ${installPath}
        Unblock-File -Path ${zipFile}
        Expand-Archive -Path ${zipFile} -DestinationPath ${installPath}
        $(Build.ArtifactStagingDirectory)\notation\notation.exe plugin list
      displayName: 'Install Notation Azure KeyVault $(notation_kv_version) Plugin '


