trigger: none

parameters:
- name: ImageHash
  displayName: ImageHash of the image to sign
  type: string
- name: ContainerRegistry
  displayName: Container Registry Service Connection
  default: georgd
  values:
    - georgd
    - gdcontaineragent

variables:
- name: vmImage
  value: 'windows-latest'
- name: notationUrl
  value: 'https://github.com/notaryproject/notation/releases/download/v1.0.0-rc.7/notation_1.0.0-rc.7_windows_amd64.zip'

jobs:
- job: 'SignAgentImage'
  displayName Sign Agent Image
pool:
    vmImage: $(vmImage)
  
steps:
  - pwsh: |
      Invoke-WebRequest -Uri $(notationUrl) -OutFile $(Build.ArtifactStagingDirectory)\notation.zip
      Unblock-File -Path $(Build.ArtifactStagingDirectory)\notation.zip
      Expand-Archive -Path $(Build.ArtifactStagingDirectory)\notation.zip -DestinationPath $(Build.ArtifactStagingDirectory)\notation\ -Force
      Get-ChildItem $(Build.ArtifactStagingDirectory)\notation\
    displayName: 'Download Notation Package'