trigger: none

parameters:
- name: KVName
  displayName: Name of Key Vault
  default: KV-Sign
- name: CodeSignName
  displayName: Name of the Code Signing Certificate in Key Vault
- name: ContainerRegistry
  displayName: Container Registry Service Connection
  default: georgd
  values:
    - georgd
    - gdcontaineragent
- name: ImageHash
  displayName: ImageHash of the image to sign
  type: string

variables:
- name: vmImage
  value: 'windows-latest'
- name: notationVersion
  value: '1.0.0-rc.7'
- name: notation_kv_version
  value: '1.0.0-rc.3'

jobs:
- job: 'SignAgentImage'
  displayName: Sign Agent Image
  pool:
      vmImage: $(vmImage)
    
  steps:
    - pwsh: |
        $installPath = "$(Build.ArtifactStagingDirectory)\notation\"
        # download zip file and checksum
        $checksumFile = "notation_$(notationVersion)_checksums.txt"
        $zipFile = "notation_$(notationVersion)_windows_amd64.zip"
        Invoke-WebRequest -Uri "https://github.com/notaryproject/notation/releases/download/v$(notationVersion)/${checkSumFile}" -OutFile ${checksumFile}
        Invoke-WebRequest -Uri "https://github.com/notaryproject/notation/releases/download/v$(notationVersion)/${zipFile}" -OutFile ${zipFile}
        # validate checksum
        $checksum = (Get-Content ${checksumFile} | Select-String -List ${zipFile}).Line.Split() | Where-Object {$_}
        If ($checksum[0] -ne (Get-FileHash -Algorithm SHA256 $checksum[1]).Hash) {
          throw "$($checksum[1]): Failed"
        }
        # install notation
        Unblock-File -Path ${zipFile}
        Expand-Archive -Path ${zipFile} -DestinationPath $(Build.ArtifactStagingDirectory)\notation\ -Force
        $(Build.ArtifactStagingDirectory)\notation\notation.exe version
      displayName: 'Download Notation $(notationVersion) Package'
    - pwsh: |
        $installPath = "${env:AppData}\notation\plugins\azure-kv"
        # download zip file and checksum
        $checksumFile = "notation-azure-kv_$(notation_kv_version)_checksums.txt"
        $zipFile = "notation-azure-kv_$(notation_kv_version)_windows_amd64.zip"
        Invoke-WebRequest -Uri "https://github.com/Azure/notation-azure-kv/releases/download/v$(notation_kv_version)/${checksumFile}" -OutFile ${checksumFile}
        Invoke-WebRequest -Uri "https://github.com/Azure/notation-azure-kv/releases/download/v$(notation_kv_version)/${zipFile}" -OutFile ${zipFile}
        # validate checksum
        $checksum = (Get-Content ${checksumFile} | Select-String -List ${zipFile}).Line.Split() | Where-Object {$_}
        If ($checksum[0] -ne (Get-FileHash -Algorithm SHA256 $checksum[1]).Hash) {
          throw "$($checksum[1]): Failed"
        }
        # install the plugin
        Unblock-File -Path ${zipFile}
        Expand-Archive -Path ${zipFile} -DestinationPath ${installPath}
        $(Build.ArtifactStagingDirectory)\notation\notation.exe plugin list
      displayName: 'Install Notation Azure KeyVault $(notation_kv_version) Plugin '
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'MCAPS-CH-georgd(d0871d2e-75c2-4b10-bd2c-38f80979d9cb)'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $KEY_ID=$(az keyvault certificate show -n $(CodeSignName) --vault-name $(KVName) --query 'kid' -o tsv)
          $KEY_ID


