apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: agent-win
  namespace: {{ .Values.namespace }}
spec:
  serviceName: agent-win
  replicas: 1
  selector:
    matchLabels:
      app: agent-win
  template:
    metadata:
      labels:
        app: agent-win
        version: "1.0"
    spec:
      containers:
      - name: agent-win
        image: {{ .Values.repo }}/pipeline-agent:{{ .Values.tag }}
        imagePullPolicy: IfNotPresent
        env:
          - name: VSTS_AGENT_INPUT_URL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: azp_url
          - name: VSTS_AGENT_INPUT_AUTH
            value: 'pat'
          - name: VSTS_AGENT_INPUT_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: azp_token
          - name: VSTS_AGENT_INPUT_POOL
            value: '{{ .Values.poolName }}'
          - name: RUN_ONCE
            value: '{{ .Values.runOnce }}'
      tolerations:
        - key: node.kubernetes.io/os
          operator: Equal
          value: windows
          effect: NoSchedule
      nodeSelector:
        kubernetes.io/os: windows

