apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: pipeline-trigger-auth
  namespace: {{ .Values.namespace }}
spec:
  secretTargetRef:
    - parameter: organizationURL
      name: azdevops
      key: azp_url
    - parameter: personalAccessToken
      name: azdevops
      key: azp_token
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: agent-linux-scaledjob
  namespace: {{ .Values.namespace }}
spec:
  jobTargetRef:
    parallelism: 5
    completions: 1
    template:
      spec:
        containers:
        - name: agent-linux
          image: {{ .Values.repo }}/pipeline-agent:{{ .Values.tag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: AZP_URL
              valueFrom:
                secretKeyRef:
                  name: azdevops
                  key: azp_url
            - name: AZP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: azdevops
                  key: azp_token
            - name: AZP_POOL
              value: '{{ .Values.poolName }}'
            - name: RUN_ONCE
              value: '{{ .Values.runOnce }}'
        tolerations:
          - key: node.kubernetes.io/os
            operator: Equal
            value: windows
            effect: NoSchedule
        nodeSelector:
          kubernetes.io/os: linux
  pollingInterval: 1
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  triggers:
  - type: azure-pipelines
    metadata:
      poolID: "{{ .Values.poolId }}"
      targetPipelinesQueueLength: "1"
    authenticationRef:
     name: pipeline-trigger-auth
