apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: agent-linux
  namespace: {{ .Values.namespace }}
spec:
  serviceName: agent-linux
  replicas: 1
  selector:
    matchLabels:
      app: agent-linux
  template:
    metadata:
      labels:
        app: agent-linux
        version: "1.0"
    spec:
      containers:
      - name: agent-linux
        image: {{ .Values.repo }}/pipeline-agent:{{ .Values.tag }}
        imagePullPolicy: IfNotPresent
        env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: azp_url
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: azp_token
          - name: AZP_POOL
            value: '{{ .Values.poolName }}'
          - name: RUN_ONCE
            value: '{{ .Values.runOnce }}'
      nodeSelector:
        kubernetes.io/os: linux

