# escape=`

# Use the latest Windows Server Core image with .NET Framework 4.8 SDK.
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

# Restore the default Windows shell for correct batch processing below.
SHELL ["cmd", "/S", "/C"]

# Download the Build Tools bootstrapper.
ADD https://aka.ms/vs/16/release/vs_professional.exe C:\TEMP\vs_professional.exe

# Install Visual Studio Enterprise excluding workloads and components with known issues.
RUN C:\TEMP\vs_professional.exe --quiet --wait --norestart --nocache `
    --add Microsoft.VisualStudio.Workload.CoreEditor `
    --add Microsoft.VisualStudio.Workload.Azure `
    --add Microsoft.VisualStudio.Workload.Data `
    --add Microsoft.VisualStudio.Workload.ManagedDesktop `
    --add Microsoft.VisualStudio.Workload.NetCoreTools `
    --add Microsoft.VisualStudio.Workload.NetWeb `
    --add Microsoft.VisualStudio.Workload.Node `
    --add Microsoft.Net.ComponentGroup.4.6.2.DeveloperTools `
    --add Microsoft.Net.ComponentGroup.4.7.DeveloperTools `
    --add Microsoft.Net.ComponentGroup.4.7.1.DeveloperTools `
    --add Microsoft.Net.ComponentGroup.4.7.2.DeveloperTools `
    --add Microsoft.Net.ComponentGroup.4.8.DeveloperTools `
    --includeRecommended `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 `
    --remove Microsoft.VisualStudio.Component.Windows81SDK `
 || IF "%ERRORLEVEL%"=="3010" EXIT 0

ENV VSTS_AGENT_INPUT_URL=https://dev.azure.com
ENV VSTS_AGENT_INPUT_AUTH=pat
ENV VSTS_AGENT_INPUT_POOL=default
ENV VSTS_AGENT_INPUT_AGENT=$COMPUTERNAME 
ENV VSTS_AGENT_INPUT_TOKEN="tokenvalue"

WORKDIR /agent
COPY LaunchAgent.ps1 /agent
CMD powershell -File .\LaunchAgent.ps1
